Repository rthurston1/Team01-Web-Application-Cherish, pull requests merged in 2024-11, with the labels that each got.

#34 Fixed css bug that affects all pages. Changes affect only Calendar page for this commit
  front-end/src/pages/calendar/stylesCalendar.css
Labels: bug

#36 [NEW FEATURE] Implement a persistent navigational menu of buttons
  front-end/src/eventhub/Events.js
  front-end/src/index.html
  front-end/src/main.js
  front-end/src/nav/NavigationComponent.js
  front-end/src/nav/stylesNav.css
  front-end/src/pages/calendar/CalendarComponent.js
  front-end/src/pages/main/BaseComponent.js
  front-end/src/pages/main/stylesBase.css
Labels: enhancement

#81 Created folders for everyone for sequence diagrams
  jesse-goldman
  team/m3/anugrah-george/When user clicks on previous and next months 2.png
  team/m3/anugrah-george/sequenceDiagramGeorge.md
  team/m3/jesse-goldman/jesse.md
  team/m3/liam-campbell/sequenceDiagramLiam
  team/m3/nikolay-ostroukhov/sequenceDiagram_niko
  team/m3/robert-thurston/sequenceDiagram_robert
  team/m3/samuel-hernandez/sequenceDiagramSam
  team/m3/wacil-volitaire/sequenceDiagramWacil
Labels: documentation

#84 [FEATURE] Add delete and edit buttons to each emotion log entry in the day page.
  front-end/src/BaseComponent.js
  front-end/src/eventhub/EventHub.js
  front-end/src/eventhub/Events.js
  front-end/src/img/check-in-icon.svg
  front-end/src/img/x-icon.svg
  front-end/src/main.js
  front-end/src/pages/check-in/CheckInComponent.js
  front-end/src/pages/day/DayComponent.js
  front-end/src/pages/day/stylesDay.css
  front-end/src/services/DatabaseService.js
  front-end/src/services/Service.js
  team/reports/nikolay-ostroukhov.md
Labels: enhancement
